# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Linked_ARM_Service_Connection'
    subscriptionId: '8170716f-eeeb-4744-988a-d267a5373048'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'linkedarm1rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'https://linkedarm1store.blob.core.windows.net/templates/azuredeploy.json?sp=r&st=2021-01-18T04:26:59Z&se=2021-01-18T12:26:59Z&spr=https&sv=2019-12-12&sr=b&sig=g2tkMlCOy%2FYqsyD340%2F%2BLt8zy%2BSRog6UKiWFHER5nQw%3D'
    csmParametersFile: 'https://linkedarm1store.blob.core.windows.net/templates/azuredeploydev.parameters.json?sp=r&st=2021-01-18T04:27:39Z&se=2021-01-18T12:27:39Z&spr=https&sv=2019-12-12&sr=b&sig=Lj4nG55My2mNA3TVZCuda1gRu0GOjbdsmsEiixoM%2BIA%3D'
    deploymentMode: 'Incremental'
pool:
  vmImage: 'ubuntu-latest'


